### ISSUE TITLE
Button combo to enable the upscaler doesn’t work on steam deck

### ISSUE THREAD

**Issue by Ann0ying** [PureDark/VRisingDLSSMod#1]
Binding the key combo to a button in steam overlay doesn’t turn on the upscaler on. 

Is it possible to make it run by default through the config file?

**Comment by PureDark** [comment]
I am not sure whether it will work on Steam Deck though, I can't test it.
And upscalers must only be turned on after the player loads into a world, too much trouble to detect it so I leave it to the player to turn it on when finishing loading.
My implementation for FSR2 on DX11 game is to create a new DX12 device to handle the upscaling, which might not work too well with proton, since it's using both DX11 and DX12 at the same time, not sure whether proton can handle this.

**Comment by Ann0ying** [comment]
Hmm, got it. 

Would it be possible to re-bind the "enable" shortcut to a single key, maybe? That way I'll be able to check if that's a proton issue, or some button-combo issue.

**Comment by PureDark** [comment]
Well the C# part's source code is right here in this repo, you can just clone it and bulid the project yourself, you can find the hotkey bindings in UpscaleManager.cs

**Comment by Ann0ying** [comment]
I definitely would if I understood how all this compiling stuff worked. Thanks anyways
